---
spring: 
    profiles: dev
    h2:
        console:
            path: /h2
    jpa:
        show-sql: false
spms:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create

office:
    datasource:
        url: jdbc:h2:mem:testdbforoffice
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: none

---

spring:
    profiles: dev-ext
    h2:
        console:
            path: /h2
    jpa:
        show-sql: false
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
spms:
    datasource:
        url: jdbc:postgresql://localhost:5432/spms
        driverClassName: org.postgresql.Driver
        username: spms_user
        password: asd
    jpa:
        hibernate:
            ddl-auto: update

office:
    datasource:
        url: jdbc:mysql://localhost:3306/office
        driverClassName: com.mysql.jdbc.Driver
        username: office_user
        password: qwer1234
    jpa:
        hibernate:
            ddl-auto: none

