---
spring: 
    profiles: dev
    h2:
        console:
            path: /h2
    jpa:
        show-sql: false
spms:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create

office:
    datasource:
        url: jdbc:h2:mem:testdbforoffice
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: none

---

spring:
    profiles: dev-ext
    h2:
        console:
            path: /h2
    jpa:
        show-sql: false
spms:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create

office:
    datasource:
        url: jdbc:mysql://localhost:3306/office
        driverClassName: com.mysql.jdbc.Driver
        username: office_user
        password: qwer1234
    jpa:
        hibernate:
            ddl-auto: none
# azert kellett a ket db config class hogy ezeket itt kulon lehssen configolni es amig test addig create de majd ha eles lesz akkor az office none
#